spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ""
            clientSecret: ""
            scope: openid,profile,email,https://www.googleapis.com/auth/youtube

logging:
  level:
    com.springbootlearning: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.web: TRACE
    org.springframework.web.reactive: TRACE
